#!/bin/bash
#
#  Command Line Interface to start all services associated with the Tutorial
#
#  For this tutorial the commands are merely a convenience script to run docker or docker-compose
#
#  Each services script can be run using either docker-compose (the external tool with the hyphen -) 
#  or docker compose (the newer version directly bundled with Docker with a space )
#
#  if you start up with the following command:
#
#  ./services start legacy
#  ./services stop
# This will force the script to use docker-compose which may be more reliable in 
# some cases (or if an older version of Docker is being used)
#
# =================================================================
# Local variables
# =================================================================
set -e

DOCKER_CMD="docker-compose"
USAGE="usage: services [help | start [test] | stop]"

##Parameters handle
if [[ $# < 1 || $# > 2 ]]; then	
	echo "Illegal number of parameters"
	echo $USAGE
	exit 1;
fi

if [[ $# == 2 && "$1" == "start" ]]; then
	if [[ "$2" == "test" ]]; then
		DOCKER_CMD="$DOCKER_CMD --profile test"
	else
		echo "Wrong parameter"
		echo $USAGE
		exit 1;
	fi
fi
# =================================================================
# Script functions()
# =================================================================
loadData () {
	docker run --rm -v $(pwd)/src/import-initial-context-data.sh:/import-initial-context-data.sh: \
		--network fiware_arduino_default \
        --entrypoint /bin/ash curlimages/curl import-initial-context-data.sh
	waitForIoTAgent
	echo ""
}
# Display the table of running services
displayServices () {
	echo ""
	docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" --filter label="com.wordpress.fcosfc=fiware_arduino"
	echo ""
}
# Run when ./services stop
stoppingContainers () {
	CONTAINERS=$(docker ps --filter "label=com.wordpress.fcosfc=fiware_arduino" -aq)
	if [[ -n $CONTAINERS ]]; then 
		echo "Stopping containers"
		docker rm -f $CONTAINERS || true
	fi
	VOLUMES=$(docker volume ls -qf dangling=true) 
	if [[ -n $VOLUMES ]]; then 
		echo "Removing old volumes"
		docker volume rm $VOLUMES || true
	fi
	NETWORKS=$(docker network ls  --filter "label=com.wordpress.fcosfc=fiware_arduino" -q) 
	if [[ -n $NETWORKS ]]; then 
		echo "Removing tutorial networks"
		docker network rm $NETWORKS || true
	fi
}
#Create Docker images
addDatabaseIndex () {
    #MongoDB
	printf "Adding appropriate \033[1mMongoDB\033[0m indexes for \033[1;34mOrion\033[0m  ..."
	docker exec  db-mongo mongo --eval '
	conn = new Mongo();db.createCollection("orion");
	db = conn.getDB("orion");
	db.createCollection("entities");
	db.entities.createIndex({"_id.servicePath": 1, "_id.id": 1, "_id.type": 1}, {unique: true});
	db.entities.createIndex({"_id.type": 1}); 
	db.entities.createIndex({"_id.id": 1});' > /dev/null

	docker exec  db-mongo mongo --eval '
	conn = new Mongo();db.createCollection("orion-openiot");
	db = conn.getDB("orion-openiot");
	db.createCollection("entities");
	db.entities.createIndex({"_id.servicePath": 1, "_id.id": 1, "_id.type": 1}, {unique: true});
	db.entities.createIndex({"_id.type": 1}); 
	db.entities.createIndex({"_id.id": 1});' > /dev/null
	echo -e " \033[1;32mdone\033[0m"
}
# =================================================================
# Wait functions()
# =================================================================
#Mongo DB
waitForMongo () {
	echo -e "\n⏳ Waiting for \033[1mMongoDB\033[0m to be available\n"
	while ! [ `docker inspect --format='{{.State.Health.Status}}' db-mongo` == "healthy" ]
	do 
		sleep 1
	done
}
# Orion Context Broker
waitForOrion () {
	echo -e "\n⏳ Waiting for \033[1;34mOrion\033[0m to be available\n"

	while ! [ `docker inspect --format='{{.State.Health.Status}}' fiware-orion` == "healthy" ]
	do
	  echo -e "Context Broker HTTP state: " `curl -s -o /dev/null -w %{http_code} 'http://localhost:1026/version'` " (waiting for 200)"
	  sleep 1
	done
}

#IOT agent initialisation
waitForIoTAgent () {
	echo -e "\n⏳ Waiting for \033[1;36mIoT-Agent\033[0m to be available\n"
	while ! [ `docker inspect --format='{{.State.Health.Status}}' fiware-iot-agent` == "healthy" ]

	do 
	  echo -e "IoT Agent HTTP state: " `curl -s -o /dev/null -w %{http_code} 'http://localhost:4041/version'` " (waiting for 200)"
	  sleep 1
	done
}
# =================================================================
# Main functions()
# =================================================================
command="$1"
case "${command}" in
	"help")
		echo $USAGE
		;;
	"start")
		export $(cat docker/.env | grep "#" -v)
		stoppingContainers
		echo -e "Starting containers: \033[1;34mOrion\033[0m and a \033[1mMongoDB\033[0m database."
		echo -e "- \033[1;34mOrion\033[0m is the context broker"
		echo ""		
		${DOCKER_CMD} -f docker/docker-compose.yaml up -d --remove-orphans
		waitForMongo
		addDatabaseIndex
		waitForOrion
		loadData
		displayServices
		echo -e "Now open \033[4mhttp://localhost:3000/device/monitor\033[0m"
		;;
	"stop")
		export $(cat docker/.env | grep "#" -v)
		stoppingContainers
		;;
	*)
		echo "Command not Found."
		echo $USAGE
		exit 127;
		;;
esac