
# Dockerfile: image definition for an MQTT client.
#   Scripts must be injected as volumes in /opt/mqtt-client
# 
FROM alpine:3.14
RUN apk add --no-cache mosquitto-clients
ENTRYPOINT [ "/opt/mqtt-client/init.sh" ]